package databaseproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AccountClosure extends javax.swing.JFrame {

    int accountID, userloginID, customerID;

    /**
     * Creates new form AccountClosure
     */
    public AccountClosure(int accountID, int userloginID, int customerID) {
        initComponents();
            ImageIcon background_img= new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\DatabaseProject\\src\\databaseproject\\AccountClosure.jpg");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(400, 329,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 400,329);
                     this.add(backgrnd);
        this.accountID = accountID;
        this.userloginID = userloginID;
        this.customerID = customerID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        YesClosure = new javax.swing.JButton();
        NoClosure = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Do you want to close your account?");

        YesClosure.setBackground(new java.awt.Color(129, 228, 218));
        YesClosure.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        YesClosure.setText("Yes");
        YesClosure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 138), 4));
        YesClosure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesClosureActionPerformed(evt);
            }
        });

        NoClosure.setBackground(new java.awt.Color(204, 0, 51));
        NoClosure.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NoClosure.setText("No");
        NoClosure.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        NoClosure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoClosureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(YesClosure, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NoClosure, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoClosure)
                    .addComponent(YesClosure))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YesClosureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesClosureActionPerformed
        // TODO add your handling code here:
        closeAccount();
    }//GEN-LAST:event_YesClosureActionPerformed

    private void NoClosureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoClosureActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenuFrame mm1 = new MainMenuFrame(this.userloginID);
        mm1.setVisible(true);
    }//GEN-LAST:event_NoClosureActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NoClosure;
    private javax.swing.JButton YesClosure;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    void closeAccount() {
        try {
            String user = "root";
            String password = "seecs@123";

            //Getting connection to the database
            Connection myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", user, password);
            // Creating a statement
            Statement myStmt = myCon.createStatement();
            ResultSet myrs;
            
            myStmt.executeUpdate("update account set accountstatustypeid = 1 where accountid = " + this.userloginID);
            JOptionPane.showMessageDialog(null, "Account Successfully Closed");
            dispose();
            mainFrame m1 = new mainFrame();
            m1.setVisible(true);

        } catch (Exception e) {
            MainMenuFrame mm1 = new MainMenuFrame(this.userloginID);
            mm1.setVisible(true);
        }

    }

}
