package databaseproject;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author waniya_mustafa
 */
public class adminMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form adminMainMenu
     */
    public adminMainMenu() {
        initComponents();
         ImageIcon background_img= new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\DatabaseProject\\src\\databaseproject\\adminMainMenu.jpeg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(1200, 700,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 1200,700);
                     this.add(backgrnd);
//                     bankLogBtn.setOpaque(true);
                     userInfoBtn.setOpaque(true);
//                     createUserBtn.setOpaque(true);
                     deleteUserBtn.setOpaque(true);
                     transactionHistoryBtn.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteUserBtn = new javax.swing.JButton();
        userInfoBtn = new javax.swing.JButton();
        transactionHistoryBtn = new javax.swing.JButton();
        transactionHistoryBtn1 = new javax.swing.JButton();
        deleteUserBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Menu");

        deleteUserBtn.setBackground(new java.awt.Color(129, 228, 218));
        deleteUserBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        deleteUserBtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteUserBtn.setText("Deactivate Account");
        deleteUserBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        deleteUserBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });

        userInfoBtn.setBackground(new java.awt.Color(129, 228, 218));
        userInfoBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        userInfoBtn.setForeground(new java.awt.Color(0, 0, 0));
        userInfoBtn.setText("User Information");
        userInfoBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        userInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInfoBtnActionPerformed(evt);
            }
        });

        transactionHistoryBtn.setBackground(new java.awt.Color(129, 228, 218));
        transactionHistoryBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transactionHistoryBtn.setForeground(new java.awt.Color(0, 0, 0));
        transactionHistoryBtn.setText("View Transaction History");
        transactionHistoryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        transactionHistoryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionHistoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryBtnActionPerformed(evt);
            }
        });

        transactionHistoryBtn1.setBackground(new java.awt.Color(129, 228, 218));
        transactionHistoryBtn1.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transactionHistoryBtn1.setForeground(new java.awt.Color(0, 0, 0));
        transactionHistoryBtn1.setText("Activate Account");
        transactionHistoryBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        transactionHistoryBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transactionHistoryBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryBtn1ActionPerformed(evt);
            }
        });

        deleteUserBtn1.setBackground(new java.awt.Color(129, 228, 218));
        deleteUserBtn1.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        deleteUserBtn1.setForeground(new java.awt.Color(0, 0, 0));
        deleteUserBtn1.setText("Back to Main Menu");
        deleteUserBtn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        deleteUserBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteUserBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteUserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(863, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transactionHistoryBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(transactionHistoryBtn)
                                .addComponent(userInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(deleteUserBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(userInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(transactionHistoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(transactionHistoryBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(deleteUserBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        deleteUserForm d1 = new deleteUserForm();
        d1.setVisible(true);
        
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void userInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInfoBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        
        adminUserInfo f1 = new adminUserInfo();
        f1.setVisible(true);
    }//GEN-LAST:event_userInfoBtnActionPerformed

    private void transactionHistoryBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryBtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        ActivateAccount a1 = new ActivateAccount();
        a1.setVisible(true);
        
    }//GEN-LAST:event_transactionHistoryBtn1ActionPerformed

    private void transactionHistoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        adminTransactionHistory t1 = new adminTransactionHistory();
        t1.setVisible(true);
    }//GEN-LAST:event_transactionHistoryBtnActionPerformed

    private void deleteUserBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtn1ActionPerformed
        // TODO add your handling code here:
        dispose();
        mainFrame m1 = new mainFrame();
        m1.setVisible(true);
    }//GEN-LAST:event_deleteUserBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JButton deleteUserBtn1;
    private javax.swing.JButton transactionHistoryBtn;
    private javax.swing.JButton transactionHistoryBtn1;
    private javax.swing.JButton userInfoBtn;
    // End of variables declaration//GEN-END:variables
}
