/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproject;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author DELL
 */
public class adminUserInfo extends javax.swing.JFrame {
    String CNIC;

    /**
     * Creates new form adminUserInfo
     */
    public adminUserInfo() {
        initComponents();
            ImageIcon background_img= new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\DatabaseProject\\src\\databaseproject\\userInfo.jpeg","");
          Image  img= background_img.getImage();
          Image temp_img=img.getScaledInstance(537,337,Image.SCALE_SMOOTH);
           background_img=new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
                     backgrnd.setBounds(0, 0, 537,337);
                     this.add(backgrnd);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        infoAccountID = new javax.swing.JTextField();
        infoProceedBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter the CNIC to see customer details:");

        infoAccountID.setBackground(new java.awt.Color(204, 204, 204));
        infoAccountID.setFont(new java.awt.Font("Arima Madurai", 0, 18)); // NOI18N
        infoAccountID.setForeground(new java.awt.Color(0, 0, 0));
        infoAccountID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        infoAccountID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoAccountIDActionPerformed(evt);
            }
        });

        infoProceedBtn.setBackground(new java.awt.Color(0, 153, 153));
        infoProceedBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        infoProceedBtn.setForeground(new java.awt.Color(255, 255, 255));
        infoProceedBtn.setText("Proceed");
        infoProceedBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 3, true));
        infoProceedBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoProceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoProceedBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(51, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(infoAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(infoProceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(infoAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoProceedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void infoAccountIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoAccountIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoAccountIDActionPerformed

    private void infoProceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoProceedBtnActionPerformed
        // TODO add your handling code here:
        this.CNIC = (this.infoAccountID.getText());
        dispose();
        userInformationForm f1 = new userInformationForm(this.CNIC);
        f1.showInfo();
        f1.setVisible(true);
    }//GEN-LAST:event_infoProceedBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField infoAccountID;
    private javax.swing.JButton infoProceedBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    


}
