package databaseproject;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author waniya_mustafa
 */
public class ChangePassword extends javax.swing.JFrame {

    int accountID, userloginID, customerID;

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword(int accountID, int userloginID, int customerID) {
        initComponents();
        ImageIcon background_img = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\DatabaseProject\\src\\databaseproject\\pss.jpg", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(720, 536, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 720, 536);
        this.add(backgrnd);
        pssBtn.setOpaque(true);
        this.accountID = accountID;
        this.userloginID = userloginID;
        this.customerID = customerID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newpssfield = new javax.swing.JPasswordField();
        pssBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        oldpssfield = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newpssfield.setBackground(new java.awt.Color(204, 204, 204));
        newpssfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        newpssfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 157, 228), 3, true));
        newpssfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpssfieldActionPerformed(evt);
            }
        });

        pssBtn.setBackground(new java.awt.Color(153, 153, 255));
        pssBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        pssBtn.setText("Change Password");
        pssBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 204), 3, true));
        pssBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel1.setText("Enter Old Password");

        jLabel2.setFont(new java.awt.Font("Arima Madurai", 1, 22)); // NOI18N
        jLabel2.setText("Enter New Password");

        oldpssfield.setBackground(new java.awt.Color(204, 204, 204));
        oldpssfield.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        oldpssfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(151, 157, 228), 3, true));
        oldpssfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldpssfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(409, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(newpssfield, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oldpssfield, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldpssfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newpssfield, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pssBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newpssfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpssfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpssfieldActionPerformed

    private void pssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssBtnActionPerformed
        // TODO add your handling code here:
        changePassword();
    }//GEN-LAST:event_pssBtnActionPerformed

    private void oldpssfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldpssfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldpssfieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField newpssfield;
    private javax.swing.JPasswordField oldpssfield;
    private javax.swing.JButton pssBtn;
    // End of variables declaration//GEN-END:variables

    void changePassword() {
        try {
            System.out.println("ChangePassword()");
            //selecting account from userloginid
            String user = "root";
            String password = "seecs@123";

            //Getting connection to the database
            Connection myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", user, password);
            // Creating a statement
            Statement myStmt = myCon.createStatement();
            ResultSet myrs;

            String oldPassword = "null";
            String enteredPassword = oldpssfield.getText();
            myrs = myStmt.executeQuery("select userpassword from userlogins where userloginid = " + this.userloginID);
            if (myrs.next()) {
                oldPassword = myrs.getString("userpassword");
            }
            System.out.println("UserPassword: " + oldPassword);
            if (!oldPassword.equals(enteredPassword)) {
                dispose();
                JOptionPane.showMessageDialog(null, "Old password mismatch!\n Try again.");
                throw new Exception();
            }
            
            String newPassword = newpssfield.getText();
            System.out.println("newPass: " + newPassword + " userloginid: " + this.userloginID);
            //updating the password in the database
            myStmt.executeUpdate("update userlogins set userpassword = '" + newPassword + "' where userloginid = " + this.userloginID + ";");
            dispose();
            JOptionPane.showMessageDialog(null, "Password Changed Succesfully!");
            MainMenuFrame mm1 = new MainMenuFrame(this.userloginID);
            mm1.setVisible(true);
            
            
        } catch (Exception e) {
            e.printStackTrace();
            MainMenuFrame mm1 = new MainMenuFrame(this.userloginID);
            mm1.setVisible(true);
        }
    }

}
