package databaseproject;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class MainMenuFrame extends javax.swing.JFrame {
    
    int userLoginId;
    int accountID;
    int customerID;

    /**
     * Creates new form MainMenuFrame
     */
    public MainMenuFrame(int userLoginId) {
        
        initComponents();
        ImageIcon background_img = new ImageIcon("C:\\Users\\DELL\\Documents\\NetBeansProjects\\DatabaseProject\\src\\databaseproject\\userMainMenu.jpg", "");
        Image img = background_img.getImage();
        Image temp_img = img.getScaledInstance(1244, 706, Image.SCALE_SMOOTH);
        background_img = new ImageIcon(temp_img);
        JLabel backgrnd = new JLabel("", background_img, JLabel.CENTER);
        backgrnd.setBounds(0, 0, 1244, 706);
        this.add(backgrnd);
        changePssBtn.setOpaque(true);
        cashDepositBtn.setOpaque(true);
        cashWithdrawlBtn.setOpaque(true);
        balanceInquiryBtn.setOpaque(true);
        historyBtn.setOpaque(true);
        transferMoneyBtn.setOpaque(true);
        closeAcctBtn.setOpaque(true);
        changePssBtn.setOpaque(true);
        logOutBtn.setOpaque(true);
        this.userLoginId = userLoginId;

    }
    
    
    void updateFields(){
    
        try {
            //selecting account from userloginid
        String user = "root";
        String password = "seecs@123";

        //Getting connection to the database
        Connection myCon = DriverManager.getConnection("jdbc:mysql://localhost:3306/project", user, password);
        // Creating a statement
        Statement myStmt = myCon.createStatement();
        ResultSet myrs;
        
        //updating accountID
        myrs = myStmt.executeQuery("select accountid from userlogins where userloginid = " + this.userLoginId + ";");
        if (myrs.next())
            this.accountID = myrs.getInt("accountid");
        
        //updating customerID
        myrs = myStmt.executeQuery("select customerid from account where accountid = " + this.accountID + ";");
        if (myrs.next())
            this.customerID = myrs.getInt("customerid");
        
        
        
        }
        catch (Exception e){
            
        }
       
    
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashDepositBtn = new javax.swing.JButton();
        cashWithdrawlBtn = new javax.swing.JButton();
        changePssBtn = new javax.swing.JButton();
        transferMoneyBtn = new javax.swing.JButton();
        balanceInquiryBtn = new javax.swing.JButton();
        closeAcctBtn = new javax.swing.JButton();
        historyBtn = new javax.swing.JButton();
        logOutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cashDepositBtn.setBackground(new java.awt.Color(129, 228, 218));
        cashDepositBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        cashDepositBtn.setText("Cash Deposit");
        cashDepositBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        cashDepositBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashDepositBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashDepositBtnActionPerformed(evt);
            }
        });

        cashWithdrawlBtn.setBackground(new java.awt.Color(129, 228, 218));
        cashWithdrawlBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        cashWithdrawlBtn.setText("Cash Withdrawl");
        cashWithdrawlBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        cashWithdrawlBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cashWithdrawlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashWithdrawlBtnActionPerformed(evt);
            }
        });

        changePssBtn.setBackground(new java.awt.Color(129, 228, 218));
        changePssBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        changePssBtn.setText("Change Password");
        changePssBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        changePssBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        changePssBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePssBtnActionPerformed(evt);
            }
        });

        transferMoneyBtn.setBackground(new java.awt.Color(129, 228, 218));
        transferMoneyBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        transferMoneyBtn.setText("Transfer Money");
        transferMoneyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        transferMoneyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferMoneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferMoneyBtnActionPerformed(evt);
            }
        });

        balanceInquiryBtn.setBackground(new java.awt.Color(129, 228, 218));
        balanceInquiryBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        balanceInquiryBtn.setText("Balance Inquiry");
        balanceInquiryBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        balanceInquiryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        balanceInquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInquiryBtnActionPerformed(evt);
            }
        });

        closeAcctBtn.setBackground(new java.awt.Color(129, 228, 218));
        closeAcctBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        closeAcctBtn.setText("Account Closure");
        closeAcctBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        closeAcctBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeAcctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAcctBtnActionPerformed(evt);
            }
        });

        historyBtn.setBackground(new java.awt.Color(129, 228, 218));
        historyBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        historyBtn.setText("Transaction History");
        historyBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        historyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        historyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyBtnActionPerformed(evt);
            }
        });

        logOutBtn.setBackground(new java.awt.Color(129, 228, 218));
        logOutBtn.setFont(new java.awt.Font("Arima Madurai", 1, 18)); // NOI18N
        logOutBtn.setText("Log Out");
        logOutBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(239, 121, 138), 4, true));
        logOutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(129, 228, 218));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Create New Account");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 121, 138), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(changePssBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cashWithdrawlBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(historyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeAcctBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferMoneyBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashDepositBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashWithdrawlBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cashDepositBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(historyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeAcctBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePssBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(logOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashWithdrawlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashWithdrawlBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        updateFields();
        System.out.println("accountID, customerID, userloginID" + this.accountID + this.customerID + this.userLoginId);
        cashWithdrawl c1 = new cashWithdrawl(this.userLoginId, this.customerID, this.accountID);
        c1.setVisible(true);
    }//GEN-LAST:event_cashWithdrawlBtnActionPerformed

    private void balanceInquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInquiryBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        updateFields();
        currentBalanceform cbf1 = new currentBalanceform(this.accountID, this.userLoginId, this.customerID);
        cbf1.setVisible(true);
        cbf1.updateFields();

    }//GEN-LAST:event_balanceInquiryBtnActionPerformed

    private void historyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        updateFields();
        TransactionHistory th = new TransactionHistory(this.accountID, this.userLoginId, this.customerID, 0);
        th.updateTransactionTable();
        th.setVisible(true);
    }//GEN-LAST:event_historyBtnActionPerformed

    private void cashDepositBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashDepositBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        updateFields();
        cashDeposit cD1 = new cashDeposit(this.accountID, this.userLoginId, this.customerID);
        cD1.setVisible(true);
    }//GEN-LAST:event_cashDepositBtnActionPerformed

    private void transferMoneyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferMoneyBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        updateFields();
        System.out.println("account, customer, user, " + this.accountID+ this.customerID+ this.userLoginId );
        transferMoneyFrame tmf1 = new transferMoneyFrame(this.accountID, this.customerID, this.userLoginId);
        tmf1.setVisible(true);
    }//GEN-LAST:event_transferMoneyBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        mainFrame m1 = new mainFrame();
        m1.setVisible(true);
    }//GEN-LAST:event_logOutBtnActionPerformed

    private void changePssBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePssBtnActionPerformed
        // TODO add your handling code here:
        updateFields();
        dispose();
        ChangePassword cp1 = new ChangePassword(this.accountID, this.customerID, this.userLoginId);
        cp1.setVisible(true);
    }//GEN-LAST:event_changePssBtnActionPerformed

    private void closeAcctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAcctBtnActionPerformed
        // TODO add your handling code here:
        updateFields();
        dispose();
        AccountClosure ac1 = new AccountClosure(this.accountID, this.customerID, this.userLoginId);
        ac1.setVisible(true);
        
    }//GEN-LAST:event_closeAcctBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateFields();
        dispose();
        newAccountCreationForm_1 n1 = new newAccountCreationForm_1(this.userLoginId, this.customerID, this.accountID);
        n1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balanceInquiryBtn;
    private javax.swing.JButton cashDepositBtn;
    private javax.swing.JButton cashWithdrawlBtn;
    private javax.swing.JButton changePssBtn;
    private javax.swing.JButton closeAcctBtn;
    private javax.swing.JButton historyBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JButton transferMoneyBtn;
    // End of variables declaration//GEN-END:variables
    
    










}
